name: scontroler
favicon: null
layout_spectrum: 0.8469378082081676
typography_spectrum: 0.23909735097549856
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.625
  lightness: 0.3564435027074069
  saturation: 0.4407713038381189
  rhythmicContrast: 0.0978804377373308
purpose: []
